apiVersion: 1.0.0
kind: ServiceAccount
data:
  name: vgs-cli
  vaults:
    - <your-vgs-vault-id>
  scopes:
    - name: access-logs:read
    - name: organizations:read
    - name: routes:read
    - name: routes:write
    - name: vaults:write
    - name: aliases:read
    - name: aliases:write
